// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MacAddr } from "../network";

/**
 * DHCP Server IPv4 Config
 */
export type DHCPv4ServerConfig = {
  /**
   * dhcp options
   * range start
   */
  ip_range_start: string;
  /**
   * range end [not include]
   */
  ip_range_end: string | null;
  /**
   * DHCP Server Addr e.g. 192.168.1.1
   */
  server_ip_addr: string;
  /**
   * network mask e.g. 255.255.255.0 = 24
   */
  network_mask: number;
  address_lease_time: number | null;
  /**
   * Static MAC --> IP address binding
   */
  mac_binding_records: Array<MacBindingRecord>;
};

export type DHCPv4ServiceConfig = {
  iface_name: string;
  enable: boolean;
  config: DHCPv4ServerConfig;
};

export type MacBindingRecord = {
  mac: MacAddr;
  ip: string;
  expire_time: number;
};
