// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FlowMark } from "../flow";
import type { GeoConfigKey } from "./geo.d";

export type DNSRedirectRuleConfig = {
  id: string;
  remark: string;
  enable: boolean;
  /**
   * DNS Query Result
   */
  result: Array<string>;
  /**
   * Match Domains
   */
  source: Array<DomainConfig>;
  update_at: number;
};

/**
 * DNS 配置
 */
export type DNSRuleConfig = {
  id?: string;
  name: string;
  /**
   * 优先级
   */
  index: number;
  /**
   * 是否启用
   */
  enable: boolean;
  /**
   * 过滤模式
   */
  filter: FilterResult;
  upstream_id: string;
  /**
   * 流量标记
   */
  mark: FlowMark;
  /**
   * 匹配规则列表
   */
  source: Array<RuleSource>;
  flow_id: number;
  update_at?: number;
};

export type DnsUpstreamConfig = {
  id?: string;
  remark: string;
  mode: DnsUpstreamMode;
  ips: Array<string>;
  port: number | null;
  update_at?: number;
};

export type DnsUpstreamMode =
  | { "t": "plaintext" }
  | { "t": "tls"; domain: string }
  | { "t": "https"; domain: string }
  | { "t": "quic"; domain: string };

export type DomainConfig = { match_type: DomainMatchType; value: string };

export type DomainMatchType = "plain" | "regex" | "domain" | "full";

export type FilterResult = "unfilter" | "only_ipv4" | "only_ipv6";

export type RuleSource =
  | { "t": "geo_key" } & GeoConfigKey
  | { "t": "config" } & DomainConfig;
