// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type DockerCmd = {
  image_name: string;
  restart: string | null;
  restart_max_retries: number | null;
  container_name: string | null;
  ports: Array<KeyValuePair> | null;
  environment: Array<KeyValuePair> | null;
  volumes: Array<KeyValuePair> | null;
  labels: Array<KeyValuePair> | null;
};

export type ImgPullEvent = {
  task_id: string;
  img_name: string;
  id: string;
  current: number | null;
  total: number | null;
};

export type KeyValuePair = { key: string; value: string };

export type PullImageReq = { image_name: string; tag: string | null };

export type PullImgTask = {
  id: string;
  img_name: string;
  complete: boolean;
  layer_current_info: { [key in string]?: PullImgTaskItem };
};

export type PullImgTaskItem = {
  id: string;
  current: number | null;
  total: number | null;
};
