// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type DockerCmd = {
  image_name: string;
  restart: string | null;
  restart_max_retries: number | null;
  container_name: string | null;
  ports: Array<KeyValuePair> | null;
  environment: Array<KeyValuePair> | null;
  volumes: Array<KeyValuePair> | null;
  labels: Array<KeyValuePair> | null;
};

export type KeyValuePair = { key: string; value: string };

export type PullImageReq = { image_name: string; tag: string | null };

export type PullImgTaskItem = {
  id: string | null;
  current: bigint | null;
  total: bigint | null;
};

export type PullManagerInfo = {
  tasks: { [key in string]?: { [key in string | null]?: PullImgTaskItem } };
};
