// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FlowDnsMark, WanIPRuleSource } from "../flow";

/**
 * 流控配置结构体
 */
export type FlowConfig = {
  id: string | null;
  /**
   * 是否启用
   */
  enable: boolean;
  /**
   * 流 ID
   */
  flow_id: number;
  /**
   * 匹配规则
   */
  flow_match_rules: Array<PacketMatchMark>;
  /**
   * 处理流量目标网卡, 目前只取第一个
   * 暂定, 可能会移动到具体的网卡上进行设置
   */
  flow_targets: Array<FlowTarget>;
  /**
   * 备注
   */
  remark: string;
  update_at: number;
};

export type FlowTarget = { "t": "interface"; name: string } | {
  "t": "netns";
  container_name: string;
};

/**
 * 数据包匹配该流控标志
 */
export type PacketMatchMark = {
  ip: string;
  vlan_id: number | null;
  qos: number | null;
};

/**
 * 对于外部 IP 规则
 */
export type WanIpRuleConfig = {
  id: string | null;
  index: number;
  enable: boolean;
  /**
   * 流量标记
   */
  mark: FlowDnsMark;
  /**
   * 匹配规则列表
   */
  source: Array<WanIPRuleSource>;
  remark: string;
  flow_id: number;
  override_dns: boolean;
  update_at: number;
};
