// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DomainConfig } from "./dns.d";

export type GeoDomainConfig = {
  name: string;
  key: string;
  values: Array<DomainConfig>;
};

export type GeoDomainConfigKey = { name: string; key: string };

export type GeoSiteConfig = {
  /**
   * 用这个 ID 作为文件名称
   */
  id: string | null;
  /**
   * 记录更新时间
   */
  update_at: number;
  /**
   * 文件 URL 地址
   */
  url: string;
  /**
   * 展示名称
   */
  name: string;
  /**
   * 启用状态
   */
  enable: boolean;
  /**
   * 下次更新时间
   */
  next_update_at: number;
  /**
   * 提取文件中的 key
   */
  geo_keys: Array<string>;
};

export type QueryGeoDomain = { name: string | null; key: string | null };

export type QueryGeoDomainConfig = { name: string | null };
