// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { IpConfig } from "../flow";

export type GeoIpConfig = {
  name: string;
  key: string;
  values: Array<IpConfig>;
};

/**
 * Geo IP
 */
export type GeoIpSourceConfig = {
  /**
   * 用这个 ID 作为文件名称
   */
  id: string | null;
  /**
   * 记录更新时间
   */
  update_at: number;
  /**
   * 文件 URL 地址
   */
  url: string;
  /**
   * 展示名称
   */
  name: string;
  /**
   * 启用状态
   */
  enable: boolean;
  /**
   * 下次更新时间
   */
  next_update_at: number;
};

export type QueryGeoIpConfig = { name: string | null };
