// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type AddController = {
  link_name: string;
  link_ifindex: number;
  master_name: string | null;
  master_ifindex: number | null;
};

export type BridgeCreate = { name: string };

export type ChangeZone = { iface_name: string; zone: IfaceZoneType };

/**
 * 需要创建的设备类型
 */
export type CreateDevType = "no_need_to_create" | "bridge";

export type IfaceCpuSoftBalance = { xps: string; rps: string };

export type IfaceZoneType = "undefined" | "wan" | "lan";

/**
 * 用于存储网卡信息的结构体
 */
export type NetworkIfaceConfig = {
  iface_name: string;
  create_dev_type: CreateDevType;
  controller_name: string | null;
  zone_type: IfaceZoneType;
  enable_in_boot: boolean;
  wifi_mode: WifiMode;
  /**
   * NIC XPS / RPS Config
   */
  xps_rps: IfaceCpuSoftBalance | null;
  update_at: number;
};

export type WifiMode = "undefined" | "client" | "ap";
