// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type AddController = {
  link_name: string;
  link_ifindex: number;
  master_name: string | null;
  master_ifindex: number | null;
};

export type BridgeCreate = { name: string };

export type ChangeZone = { iface_name: string; zone: IfaceZoneType };

export type IfaceCpuSoftBalance = { xps: string; rps: string };

export type IfaceZoneType = "undefined" | "wan" | "lan";
