// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type LDIAPrefix = {
  /**
   * unit: s
   */
  preferred_lifetime: number;
  /**
   * unit: s
   */
  valid_lifetime: number;
  prefix_len: number;
  prefix_ip: string;
  last_update_time: number;
};
