// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type FirewallEvent = {
  event_type: FirewallEventType;
  src_ip: string;
  dst_ip: string;
  src_port: number;
  dst_port: number;
  /**
   * TCP / UDP / ICMP
   */
  l4_proto: number;
  l3_proto: number;
  flow_id: number;
  trace_id: number;
  create_time: number;
};

export type FirewallEventType = "unknow" | "createconnect" | "disconnct";

export type FirewallKey = {
  src_ip: string;
  dst_ip: string;
  src_port: number;
  dst_port: number;
  l4_proto: number;
  l3_proto: number;
  flow_id: number;
  trace_id: number;
  create_time: number;
};

/**
 * 防火墙数据上报 metric
 */
export type FirewallMetric = {
  src_ip: string;
  dst_ip: string;
  src_port: number;
  dst_port: number;
  create_time: number;
  time: number;
  /**
   * TCP / UDP / ICMP
   */
  l4_proto: number;
  l3_proto: number;
  flow_id: number;
  trace_id: number;
  ingress_bytes: number;
  ingress_packets: number;
  egress_bytes: number;
  egress_packets: number;
};

export type FrontEndFirewallConnectData = {
  key: FirewallKey;
  value: Array<FirewallMetric>;
};

export type FrontEndFirewallMetricServiceData = {
  connects: Array<FirewallKey>;
  connect_metrics: Array<FrontEndFirewallConnectData>;
};
