// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type MSSClampServiceConfig = {
  iface_name: string;
  enable: boolean;
  /**
   * clamp size
   * PPPoE: 1500 - 8 = 1492
   */
  clamp_size: number;
  update_at: number;
};
