// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type PPPDConfig = {
  default_route: boolean;
  peer_id: string;
  password: string;
};

export type PPPDServiceConfig = {
  attach_iface_name: string;
  iface_name: string;
  enable: boolean;
  pppd_config: PPPDConfig;
};
