// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type LandscapePtyConfig = {
  shell: string;
  rows: number;
  cols: number;
  pixel_width: number;
  pixel_height: number;
};

export type LandscapePtySize = {
  rows: number;
  cols: number;
  pixel_width: number;
  pixel_height: number;
};

export type PtyInMessage = { "t": "size"; size: LandscapePtySize } | {
  "t": "data";
  data: Array<number>;
} | { "t": "exit" };

export type PtyOutMessage = { "t": "data"; data: Array<number> } | {
  "t": "exit";
  msg: string;
};

export type SessionStatus =
  | { "t": "on" }
  | { "t": "exited" } & number
  | { "t": "error" } & string;
