// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type IPV6RAConfig = {
  /**
   * 子网前缀长度, 一般是使用 64
   */
  subnet_prefix: number;
  /**
   * 子网索引
   */
  subnet_index: bigint;
  /**
   * 当前主机的 mac 地址
   */
  depend_iface: string;
  /**
   * 通告 IP 时间
   */
  ra_preferred_lifetime: number;
  ra_valid_lifetime: number;
  /**
   * RA 通告标识
   */
  ra_flag: RouterFlags;
};

export type IPV6RAServiceConfig = {
  iface_name: string;
  enable: boolean;
  config: IPV6RAConfig;
};

export type RouterFlags = {
  managed_address_config: boolean;
  other_config: boolean;
  home_agent: boolean;
  prf: number;
  nd_proxy: boolean;
  reserved: number;
};
