// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { LandscapeDnsRecordType } from "./common/dns_record_type.d";

export type CheckChainDnsResult = {
  redirect_id: string | null;
  rule_id: string | null;
  records: Array<any> | null;
  cache_records: Array<any> | null;
};

export type CheckDnsReq = {
  flow_id: number;
  domain: string;
  record_type: LandscapeDnsRecordType;
};

export type CheckDnsResult = {
  config: any | null;
  records: Array<any> | null;
  cache_records: Array<any> | null;
};
