// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FlowDnsMark } from "./flow";

export type CloudFlareMode = "plaintext" | "tls" | "https";

export type DNSResolveMode = { "t": "redirect", ips: Array<string>, } | { "t": "upstream", upstream: DnsUpstreamType, ips: Array<string>, port: number | null, } | { "t": "cloudflare", mode: CloudFlareMode, };

/**
 * DNS 配置
 */
export type DNSRuleConfig = { name: string, 
/**
 * 优先级
 */
index: number, 
/**
 * 是否启用
 */
enable: boolean, 
/**
 * 过滤模式
 */
filter: FilterResult, 
/**
 * 解析模式
 */
resolve_mode: DNSResolveMode, 
/**
 * 流量标记
 */
mark: FlowDnsMark, 
/**
 * 匹配规则列表
 */
source: Array<RuleSource>, flow_id: number, };

export type DnsUpstreamType = { "t": "plaintext" } | { "t": "tls", domain: string, } | { "t": "https", domain: string, };

export type DomainConfig = { match_type: DomainMatchType, value: string, };

export type DomainMatchType = "plain" | "regex" | "domain" | "full";

export type FilterResult = "unfilter" | "onlyipv4" | "onlyipv6";

export type RuleSource = { "t": "geokey", key: string, } | { "t": "config" } & DomainConfig;
