// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MacAddr } from "./network";

/**
 * 流控配置结构体
 */
export type FlowConfig = { 
/**
 * 是否启用
 */
enable: boolean, 
/**
 * 流 ID
 */
flow_id: number, 
/**
 * 匹配规则
 */
flow_match_rules: Array<PacketMatchMark>, 
/**
 * 处理流量目标网卡, 目前只取第一个
 */
packet_handle_iface_name: Array<FlowTarget>, 
/**
 * 备注
 */
remark: string, };

export type FlowTarget = { "t": "interface", name: string, } | { "t": "netns", container_name: string, };

/**
 * 数据包匹配该流控标志
 */
export type PacketMatchMark = { mac: MacAddr, vlan_id: number | null, qos: number | null, };
