// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type FlowDnsMark =
  | { "t": "keepgoing" }
  | { "t": "direct" }
  | { "t": "drop" }
  | { "t": "redirect"; flow_id: number }
  | { "t": "allowreuseport" };

export type IpConfig = { ip: string; prefix: number };

export type WanIPRuleSource =
  | { "t": "geokey"; country_code: string }
  | { "t": "config" } & IpConfig;
