// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type PacketMark =
  | { "t": "nomark" }
  | { "t": "direct" }
  | { "t": "drop" }
  | { "t": "redirect"; index: number }
  | { "t": "symmetricnat" }
  | { "t": "redirectnetns"; index: number };
