// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type LoginInfo = { username: string; password: string };

export type LoginResult = { success: boolean; token: string };
