// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type GetUIConfigResponse = { ui: LandscapeUIConfig; hash: string };

/**
 * auth realte config
 */
export type LandscapeAuthConfig = {
  /**
   * login user
   */
  admin_user: string | null;
  /**
   * login pass
   */
  admin_pass: string | null;
};

/**
 * Read & Write <CONFIG_PATH>/landscape.toml
 */
export type LandscapeConfig = {
  auth: LandscapeAuthConfig;
  web: LandscapeWebConfig;
  log: LandscapeLogConfig;
  store: LandscapeStoreConfig;
  metric: LandscapeMetricConfig;
  ui: LandscapeUIConfig;
};

export type LandscapeLogConfig = {
  log_path: string | null;
  debug: boolean | null;
  log_output_in_terminal: boolean | null;
  max_log_files: number | null;
};

export type LandscapeMetricConfig = {
  retention_days: bigint | null;
  batch_size: number | null;
  flush_interval_secs: bigint | null;
  max_memory: number | null;
  max_threads: number | null;
};

export type LandscapeStoreConfig = { database_path: string | null };

export type LandscapeUIConfig = {
  language?: string;
  timezone?: string;
  theme?: string;
};

/**
 * web realte config
 */
export type LandscapeWebConfig = {
  /**
   * Web Root
   */
  web_root: string | null;
  /**
   * Listen HTTP port
   */
  port: number | null;
  /**
   * Listen HTTPS port
   */
  https_port: number | null;
  /**
   * Listen address
   */
  address: string | null;
};

export type UpdateUIConfigRequest = {
  new_ui: LandscapeUIConfig;
  expected_hash: string;
};

export type WifiServiceConfig = {
  iface_name: string;
  enable: boolean;
  /**
   * hostapd config file
   */
  config: string;
  update_at: number;
};
