// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type GeoConfigKey = {
  name: string;
  key: string;
  inverse: boolean;
  attribute_key: string | null;
};

export type GeoFileCacheKey = { name: string; key: string };

export type QueryGeoKey = { name: string | null; key: string | null };
