// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type IPV6RAConfig = {
  /**
   * Router Advertisement Interval
   */
  ad_interval: number;
  /**
   * Router Advertisement Flag
   */
  ra_flag: RouterFlags;
  /**
   * Ip Source
   */
  source: Array<IPV6RaConfigSource>;
};

export type IPV6RAServiceConfig = {
  iface_name: string;
  enable: boolean;
  config: IPV6RAConfig;
  update_at?: number;
};

export type IPV6RaConfigSource =
  | { "t": "static" } & IPv6RaStaticConfig
  | { "t": "pd" } & IPv6RaPdConfig;

export type IPv6RaPdConfig = {
  depend_iface: string;
  prefix_len: number;
  subnet_index: number;
  ra_preferred_lifetime: number;
  ra_valid_lifetime: number;
};

export type IPv6RaStaticConfig = {
  /**
   * Base Prefix
   */
  base_prefix: string;
  /**
   * subnet prefix length default 64
   */
  sub_prefix_len: number;
  /**
   * index of subnet
   */
  sub_index: number;
  ra_preferred_lifetime: number;
  ra_valid_lifetime: number;
};

export type RouterFlags = {
  managed_address_config: boolean;
  other_config: boolean;
  home_agent: boolean;
  prf: number;
  nd_proxy: boolean;
  reserved: number;
};
