// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ServiceStatus = { "t": "staring" } | { "t": "running" } | {
  "t": "stopping";
} | { "t": "stop" };
