// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * CPU Usage Information
 */
export type CpuUsage = {
  /**
   * CPU Usage Percentage
   */
  usage: number;
  /**
   * CPU Name
   */
  name: string;
  /**
   * Vendor ID
   */
  vendor_id: string;
  /**
   * Brand
   */
  brand: string;
  /**
   * Frequency in MHz
   */
  frequency: number;
  /**
   * Temperature in Celsius (Optional)
   */
  temperature?: number;
};

/**
 * Landscape Runtime Status
 */
export type LandscapeStatus = {
  /**
   * Global CPU Usage Percentage
   */
  global_cpu_info: number;
  /**
   * Global/Package CPU Temperature in Celsius
   */
  global_cpu_temp?: number;
  /**
   * Per-CPU Usage Information
   */
  cpus: Array<CpuUsage>;
  /**
   * Memory Usage Information
   */
  mem: MemUsage;
  /**
   * System Uptime in Seconds
   */
  uptime: number;
  /**
   * Load Average Information
   */
  load_avg: LoadAvg;
};

/**
 * System Basic Information
 */
export type LandscapeSystemInfo = {
  /**
   * Hostname
   */
  host_name?: string;
  /**
   * System Name (e.g., Linux)
   */
  system_name?: string;
  /**
   * Kernel Version
   */
  kernel_version?: string;
  /**
   * OS Version
   */
  os_version?: string;
  /**
   * Landscape Version
   */
  landscape_version: string;
  /**
   * CPU Architecture
   */
  cpu_arch: string;
  /**
   * System Start Time (Timestamp)
   */
  start_at: number;
};

/**
 * System Load Average
 */
export type LoadAvg = {
  /**
   * Average load within one minute.
   */
  one: number;
  /**
   * Average load within five minutes.
   */
  five: number;
  /**
   * Average load within fifteen minutes.
   */
  fifteen: number;
};

/**
 * Memory Usage Information
 */
export type MemUsage = {
  /**
   * Total Memory in Bytes
   */
  total_mem: number;
  /**
   * Used Memory in Bytes
   */
  used_mem: number;
  /**
   * Total Swap in Bytes
   */
  total_swap: number;
  /**
   * Used Swap in Bytes
   */
  used_swap: number;
};
