[package]
name = "landscape-core"
version.workspace = true
edition.workspace = true

[dependencies]
landscape-common = { path = "../landscape-common" }

arc-swap = { workspace = true }
async-trait = { workspace = true }
dashmap = { workspace = true }
idna = { workspace = true }
libc = { workspace = true }
tokio = { workspace = true, features = ["rt", "sync", "macros", "time", "net"] }
tokio-util = { workspace = true }
tracing = { workspace = true }

[dev-dependencies]
tokio = { workspace = true, features = ["rt", "macros", "test-util"] }
