// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ConnectAgg = {
  ingress_bytes: number;
  ingress_packets: number;
  egress_bytes: number;
  egress_packets: number;
};

export type ConnectEventType = "unknow" | "create_connect" | "dis_connct";

export type ConnectInfo = {
  key: ConnectKey;
  event_type: ConnectEventType;
  report_time: number;
};

/** */
export type ConnectKey = {
  src_ip: string;
  dst_ip: string;
  src_port: number;
  dst_port: number;
  l4_proto: number;
  l3_proto: number;
  flow_id: number;
  trace_id: number;
  create_time: number;
};

export type ConnectMetric = {
  key: ConnectKey;
  report_time: number;
  ingress_bytes: number;
  ingress_packets: number;
  egress_bytes: number;
  egress_packets: number;
};

export type ConnectRealtimeStatus = {
  key: ConnectKey;
  ingress_bps: number;
  egress_bps: number;
  ingress_pps: number;
  egress_pps: number;
  last_metric: ConnectMetric | null;
};
