// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ConnectAgg = {
  ingress_bytes: number;
  ingress_packets: number;
  egress_bytes: number;
  egress_packets: number;
};

export type ConnectGlobalStats = {
  total_ingress_bytes: number;
  total_egress_bytes: number;
  total_ingress_pkts: number;
  total_egress_pkts: number;
  total_connect_count: number;
  last_calculate_time: number;
};

export type ConnectHistoryQueryParams = {
  start_time?: number;
  end_time?: number;
  limit?: number;
  src_ip?: string;
  dst_ip?: string;
  port_start?: number;
  port_end?: number;
  l3_proto?: number;
  l4_proto?: number;
  flow_id?: number;
  sort_key?: ConnectSortKey;
  sort_order?: SortOrder;
  status?: number;
};

export type ConnectHistoryStatus = {
  key: ConnectKey;
  src_ip: string;
  dst_ip: string;
  src_port: number;
  dst_port: number;
  l4_proto: number;
  l3_proto: number;
  flow_id: number;
  trace_id: number;
  total_ingress_bytes: number;
  total_egress_bytes: number;
  total_ingress_pkts: number;
  total_egress_pkts: number;
  last_report_time: number;
  status: number;
};

/** */
export type ConnectKey = { create_time: number; cpu_id: number };

export type ConnectMetric = {
  key: ConnectKey;
  src_ip: string;
  dst_ip: string;
  src_port: number;
  dst_port: number;
  l4_proto: number;
  l3_proto: number;
  flow_id: number;
  trace_id: number;
  report_time: number;
  ingress_bytes: number;
  ingress_packets: number;
  egress_bytes: number;
  egress_packets: number;
  status: ConnectStatusType;
};

export type ConnectRealtimeStatus = {
  key: ConnectKey;
  src_ip: string;
  dst_ip: string;
  src_port: number;
  dst_port: number;
  l4_proto: number;
  l3_proto: number;
  flow_id: number;
  trace_id: number;
  ingress_bps: number;
  egress_bps: number;
  ingress_pps: number;
  egress_pps: number;
  last_metric: ConnectMetric | null;
};

export type ConnectSortKey =
  | "time"
  | "port"
  | "ingress"
  | "egress"
  | "duration";

export type ConnectStatusType = "unknow" | "active" | "disabled";

export type IpAggregatedStats = {
  ingress_bps: number;
  egress_bps: number;
  ingress_pps: number;
  egress_pps: number;
  active_conns: number;
};

export type IpHistoryStat = {
  ip: string;
  flow_id: number;
  total_ingress_bytes: number;
  total_egress_bytes: number;
  total_ingress_pkts: number;
  total_egress_pkts: number;
  connect_count: number;
};

export type IpRealtimeStat = { ip: string; stats: IpAggregatedStats };

export type MetricChartRequest = {
  key: ConnectKey;
  resolution?: MetricResolution;
};

export type MetricResolution = "second" | "hour" | "day";

export type SortOrder = "asc" | "desc";
