// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ConnectAgg = {
  ingress_bytes: number;
  ingress_packets: number;
  egress_bytes: number;
  egress_packets: number;
};

export type ConnectEventType = "unknow" | "create_connect" | "dis_connct";

export type ConnectGlobalStats = {
  total_ingress_bytes: number;
  total_egress_bytes: number;
  total_ingress_pkts: number;
  total_egress_pkts: number;
  total_connect_count: number;
  last_calculate_time: number;
};

export type ConnectHistoryQueryParams = {
  start_time: bigint | null;
  end_time: bigint | null;
  limit: number | null;
  src_ip: string | null;
  dst_ip: string | null;
  port_start: number | null;
  port_end: number | null;
  l3_proto: number | null;
  l4_proto: number | null;
  flow_id: number | null;
  sort_key: ConnectSortKey | null;
  sort_order: SortOrder | null;
  status: number | null;
};

export type ConnectHistoryStatus = {
  key: ConnectKey;
  total_ingress_bytes: number;
  total_egress_bytes: number;
  total_ingress_pkts: number;
  total_egress_pkts: number;
  last_report_time: number;
  status: number;
};

/** */
export type ConnectKey = {
  src_ip: string;
  dst_ip: string;
  src_port: number;
  dst_port: number;
  l4_proto: number;
  l3_proto: number;
  flow_id: number;
  trace_id: number;
  create_time: number;
};

export type ConnectMetric = {
  key: ConnectKey;
  report_time: number;
  ingress_bytes: number;
  ingress_packets: number;
  egress_bytes: number;
  egress_packets: number;
  status: ConnectStatusType;
  cpu_id: number;
};

export type ConnectRealtimeStatus = {
  key: ConnectKey;
  ingress_bps: number;
  egress_bps: number;
  ingress_pps: number;
  egress_pps: number;
  last_metric: ConnectMetric | null;
};

export type ConnectSortKey =
  | "time"
  | "port"
  | "ingress"
  | "egress"
  | "duration";

export type ConnectStatusType = "unknow" | "active" | "disabled";

export type SortOrder = "asc" | "desc";
