// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SortOrder } from "./connect.d";

export type DnsHistoryQueryParams = {
  start_time: bigint | null;
  end_time: bigint | null;
  limit: number | null;
  domain: string | null;
  src_ip: string | null;
  sort_key: DnsSortKey | null;
  sort_order: SortOrder | null;
};

export type DnsMetric = {
  flow_id: number;
  domain: string;
  query_type: string;
  response_code: string;
  report_time: number;
  duration_ms: number;
  src_ip: string;
  answers: Array<string>;
};

export type DnsSortKey = "time" | "domain" | "duration";
