// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SortOrder } from "./connect.d";

export type DnsHistoryQueryParams = {
  start_time?: number;
  end_time?: number;
  limit?: number;
  offset?: number;
  domain?: string;
  src_ip?: string;
  query_type?: string;
  status?: DnsResultStatus;
  min_duration_ms?: number;
  max_duration_ms?: number;
  sort_key?: DnsSortKey;
  sort_order?: SortOrder;
  flow_id?: number;
};

export type DnsHistoryResponse = { items: Array<DnsMetric>; total: number };

export type DnsLightweightSummaryResponse = {
  total_queries: number;
  total_effective_queries: number;
  cache_hit_count: number;
  hit_count_v4: number;
  hit_count_v6: number;
  hit_count_other: number;
  total_v4: number;
  total_v6: number;
  total_other: number;
  block_count: number;
  filter_count: number;
  nxdomain_count: number;
  error_count: number;
  avg_duration_ms: number;
  p50_duration_ms: number;
  p95_duration_ms: number;
  p99_duration_ms: number;
  max_duration_ms: number;
};

export type DnsMetric = {
  flow_id: number;
  domain: string;
  query_type: string;
  response_code: string;
  status: DnsResultStatus;
  report_time: number;
  duration_ms: number;
  src_ip: string;
  answers: Array<string>;
};

export type DnsResultStatus =
  | "local"
  | "block"
  | "hit"
  | "nxdomain"
  | "filter"
  | "normal"
  | "error";

export type DnsSortKey = "time" | "domain" | "duration";

export type DnsStatEntry = { name: string; count: number; value?: number };

export type DnsSummaryQueryParams = {
  start_time: number;
  end_time: number;
  flow_id?: number;
};

export type DnsSummaryResponse = {
  total_queries: number;
  total_effective_queries: number;
  cache_hit_count: number;
  hit_count_v4: number;
  hit_count_v6: number;
  hit_count_other: number;
  total_v4: number;
  total_v6: number;
  total_other: number;
  block_count: number;
  filter_count: number;
  nxdomain_count: number;
  error_count: number;
  avg_duration_ms: number;
  p50_duration_ms: number;
  p95_duration_ms: number;
  p99_duration_ms: number;
  max_duration_ms: number;
  top_clients: Array<DnsStatEntry>;
  top_domains: Array<DnsStatEntry>;
  top_blocked: Array<DnsStatEntry>;
  slowest_domains: Array<DnsStatEntry>;
};
